const mongoose = require('mongoose');
const User = require('./User')

// connect to the database
mongoose.connect("mongodb://localhost/testdb")

run();  
// create a user 
async function run(){
    try{
        const newUser = await User.create({
            name : "Joe",
            age : 23,
            email : "CHIRAGNSUT04@gmail.com",
            hobbies: ["cricket" , "swimming" , "singing"],
            address: {
                state : "New Delhi"
            }
        })
        console.log(newUser)
    }catch(err){
        console.log(err.message);
    }
}
// _id is an autogenerated id by mongodb
